{"name": "test_assume", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_case\\test_demo_case.py:10: AssumptionFailure\n>>\tassume(a > b)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_case\\test_demo_case.py:10: AssumptionFailure\nE               >>\tassume(a > b)\nE               AssertionError: assert False\n\nC:\\Users\\段海洋\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\six.py:718: FailedAssumption"}, "attachments": [{"name": "log", "source": "1d9b57b3-094b-40e0-8efe-fd90d118905e-attachment.txt", "type": "text/plain"}], "start": 1663205850343, "stop": 1663205850575, "uuid": "5eeb302d-69b4-47f0-9156-7aa6543bbbcd", "historyId": "7f44080ab51f1f675e8b954a8c991ee2", "testCaseId": "3935ecba7ab9cd11825d5a668c644f54", "fullName": "test_case.test_demo_case#test_assume", "labels": [{"name": "tag", "value": "assume1"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_demo_case"}, {"name": "host", "value": "DESKTOP-28IKM3J"}, {"name": "thread", "value": "26192-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_demo_case"}]}